steps:
- name: node
  entrypoint: npm
  args: ["install"]
- name: node
  entrypoint: npm
  args: ["test", "reactin"]
- name: node
  entrypoint: npm
  args: ["run", "build", "reactin"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west6-docker.pkg.dev/lcarv-project/image-repository/nx-docker', '-f', "/apps/reactin", "."]
  images: ['europe-west6-docker.pkg.dev/lcarv-project/image-repository/nx-docker']
